export default{
    name:'pin',
    title:'pinTitle',
    type:'document',
    fields:[
        {
            name:'titleName',
            title:'titleTitle',
            type:'string',
        },
        {
            name:'aboutName',
            title:'aboutTitle',
            type:'string',
        },
        {
            name:'destination',
            title:'destinationTitle',
            type:'url',
        },
        {
            name:'category',
            title:'caategoryTitle',
            type:'string',
        },
        {
            name:'image',
            title:'imageTitle',
            type:'string',
            options:{
                hotspot:true 
            }
        },
        {
            name:'userId',
            title:'userIdTitle',
            type:'string',
        },
        {
            name:'postedBy',
            title:'postedTitle',
            type:'postedBy',
        },
        {
            name:'save',
            title:'saveTitle',
            type:'array',
            of:[{type:'save'}]
        },
        {
            name:'comments',
            title:'commentsTitle',
            type:'array',
            of:[{type:'comment'}]
        },
    ]
}